context:
  version: "10.0.6"

package:
  name: concurrently
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/concurrently/-/concurrently-${{ version }}.tgz
  sha256: c16ece4a4b71fe7e41779ce7581ef9e4c97176cc4306085ec134b0038bd7f767

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - concurrently --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Run commands concurrently.
  homepage: https://github.com/open-cli-tools/concurrently
  repository: https://github.com/open-cli-tools/concurrently

extra:
  recipe-maintainers:
    - danielnachun
