context:
  version: "10.0.5"

package:
  name: concurrently
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/concurrently/-/concurrently-${{ version }}.tgz
  sha256: ea6cdfa895d13a5671141fdc925a7f511c22a7b9fa542f307d4162dc9d2bea01

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - concurrently --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Run commands concurrently.
  homepage: https://github.com/open-cli-tools/concurrently
  repository: https://github.com/open-cli-tools/concurrently

extra:
  recipe-maintainers:
    - danielnachun
